PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT
    ?item
    ?bcp47
WHERE {
    SERVICE <https://query.wikidata.org/sparql> {
        ?item wdt:P506 ?bcp47.
    }
}
ORDER BY ?bcp47