PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT
    ?item
    ?bcp47
WHERE {
    SERVICE <https://query.wikidata.org/sparql> {
        ?item wdt:P305 ?bcp47.
        OPTIONAL { ?item wdt:P218 ?iso_639_1. }
        OPTIONAL { ?item wdt:P220 ?iso_639_3. }
        OPTIONAL { ?item wdt:P1798 ?iso_639_5. }
        FILTER ( ?iso_639_1 || ?iso_639_3 || ?iso_639_5 )
    }
}
ORDER BY ?bcp47