# Generated by Django 4.2.5 on 2023-09-17 08:45

import django.db.models.deletion
from django.db import migrations, models

import internationalization.models.abstract.main_fields


class Migration(migrations.Migration):
    dependencies = [
        ('internationalization', '0002_script_source_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_data', models.URLField(null=True)),
                ('added', models.DateTimeField()),
                ('deprecated', models.DateTimeField(null=True)),
                ('description',
                 models.JSONField(default=list,
                                  validators=[internationalization.models.abstract.main_fields._validator])),
                ('subtag', models.CharField(max_length=4)),
                ('iso_639_1', models.CharField(max_length=2)),
                ('iso_639_2', models.CharField(max_length=3)),
                ('iso_639_3', models.CharField(max_length=3)),
                ('iso_639_5', models.CharField(max_length=3)),
                ('macro_language',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.RESTRICT,
                                   related_name='macro_language_back',
                                   to='internationalization.language')),
                ('preferred_value',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.RESTRICT,
                                   to='internationalization.language')),
                ('scope',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.RESTRICT,
                                   to='internationalization.languagescope')),
                ('suppress_script',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.RESTRICT,
                                   to='internationalization.script')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
