# Generated by Django 4.2.5 on 2023-09-19 13:05

import django.db.models.fields.related
from django.db import migrations, models

import internationalization.models.abstract.main_fields


class Migration(migrations.Migration):
    dependencies = [
        ('internationalization', '0008_language_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_data', models.URLField(null=True)),
                ('added', models.DateTimeField()),
                ('deprecated', models.DateTimeField(null=True)),
                ('description',
                 models.JSONField(default=list,
                                  validators=[internationalization.models.abstract.main_fields._validator])),
                ('subtag', models.CharField(max_length=4, unique=True)),
                ('iso3166_1_alpha2', models.CharField(max_length=2, null=True, unique=True)),
                ('iso3166_1_alpha3', models.CharField(max_length=3, null=True, unique=True)),
                ('iso3166_1_numeric', models.IntegerField(null=True, unique=True)),
                ('comments', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionOfficialLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language',
                 models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey,
                                   to='internationalization.language')),
                ('region',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='internationalization.region')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='official_languages',
            field=models.ManyToManyField(through='internationalization.RegionOfficialLanguage',
                                         to='internationalization.language'),
        ),
        migrations.AddField(
            model_name='region',
            name='preferred_value_region',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.RESTRICT,
                                    to='internationalization.region'),
        ),
        migrations.AddConstraint(
            model_name='regionofficiallanguage',
            constraint=models.UniqueConstraint(fields=('region', 'language'), name='uq_region_official_language'),
        ),
    ]
