# Generated by Django 4.2.5 on 2023-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('internationalization', '0007_language_preferred_value_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
