# Generated by Django 4.1.8 on 2023-04-23 19:50

# from django.db import migrations
#
# from internationalization.models.language import Language
#
#
# def load_languages(apps, _schema_editor):
#     Language.objects.bulk_create([
#         L
#     ])
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('internationalization', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.RunPython(load_languages),
#     ]
